WEB = "../../covidgrowth"
CSS = "../../css"
ROLLUP = "rollup --format iife --name state --file $@ --plugin node-resolve --context window --sourcemap"

# Generate data files for web pages
[web]
deps = [
    "$(WEB)/ca-graph.min.js",
    "$(WEB)/usa-graph.min.js",
    "$(WEB)/state-graph.min.js",
    "$(WEB)/world-graph.min.js",
    "$(WEB)/state-cartogram.min.js",
    "$(WEB)/ca-graph.js",
    "$(WEB)/usa-graph.js",
    "$(WEB)/state-graph.js",
    "$(WEB)/world-graph.js",
    "$(WEB)/rankca.md",
    "$(WEB)/rankusa.md",
    "$(WEB)/rankstate.md",
    "$(WEB)/rankworld.md",
    "$(CSS)/rankca.scss",
    "$(CSS)/rankusa.scss",
    "$(CSS)/rankstate.scss",
    "$(CSS)/rankworld.scss",
]

["web/data_world.js"]
deps = ["raw-data.json", "raw2data.js", "common.js"]
exec = "node raw2data.js $< >$@"

["web/data_ca.js"]
deps = ["time_series_covid19_deaths_US.csv", "ca_raw2data.js", "common.js"]
exec = "node ca_raw2data.js $< >$@"

["web/data_usa.js"]
deps = ["time_series_covid19_deaths_US.csv", "us_raw2data.js", "common.js"]
exec = "node us_raw2data.js $< >$@"

["web/data_state.js"]
deps = ["time_series_covid19_deaths_US.csv", "state_raw2data.js", "common.js"]
exec = "node state_raw2data.js $< >$@"

["web/state-cartogram-nodes.js"]
deps = ["time_series_covid19_deaths_US.csv", "gencartogram_state.js", "common.js"]
exec = "node gencartogram_state.js $< >$@"

["$(WEB)/rank%.md"]
deps = ["web/data_%.js", "genrank_%_md.js", "genrank_md.js"]
exec = "node genrank_%_md.js >$@"

["$(CSS)/rank%.scss"]
deps = ["web/data_%.js", "genrank_%_scss.js",  "genrank_scss.js", "web/graph.js"]
exec = "node genrank_%_scss.js >$@"

["raw-data.json"]
exec = "wget --output-document=$@ https://opendata.ecdc.europa.eu/covid19/casedistribution/json/"

["time_series_covid19_deaths_US.csv"]
exec = "wget --output-document=$@ https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"

["$(WEB)/%-graph.min.js"]
deps = ["web/%-graph.js", "web/data_%.js", "web/graph.js", "web/passprint.js"]
exec = "$(ROLLUP) --plugin terser --input $<"

["$(WEB)/state-cartogram.js"]
deps = [ "web/state-cartogram.js", "web/state-cartogram-links.js", "web/state-cartogram-latlons.js", "web/state-cartogram-nodes.js"]
exec = "$(ROLLUP) --input $<"

["$(WEB)/state-cartogram.min.js"]
deps = [ "web/state-cartogram.js", "web/state-cartogram-links.js", "web/state-cartogram-latlons.js", "web/state-cartogram-nodes.js"]
exec = "$(ROLLUP) --plugin terser --input $<"

["$(WEB)/%-graph.js"]
deps = ["web/%-graph.js", "web/data_%.js", "web/graph.js"]
exec = "$(ROLLUP) --input $<"

[clean]
exec = """
rm -f web/data_world.js web/data_us.js web/data_state.js
rm -f raw-data.json time_series_covid19_deaths_US.csv
"""
