[copy]
deps = ["data.js", "index.js", "index.md"]
exec = "mkdir -p ../../covidgrowth && cp $+ *.csv ../../covidgrowth"

["data.js"]
deps = ["raw-data.json", "raw2data.js"]
exec = "node raw2data.js $< >$@"

["raw-data.json"]
exec = "wget --output-document=$@ https://opendata.ecdc.europa.eu/covid19/casedistribution/json/"

[clean]
exec = """
rm -f data.js COVID-19-geographic-disbtribution-worldwide.xlsx
rm -rf ../../covidgrowth
"""
