WEB = "../../covidgrowth"
CSS = "../../css"
ROLLUP = "rollup --format iife --name state --file $@ --plugin node-resolve --context window --sourcemap"

# Generate data files for web pages
[web]
deps = [
    "$(WEB)/ca.min.js",
    "$(WEB)/usa.min.js",
    "$(WEB)/state.min.js",
    "$(WEB)/world.min.js",
    "$(WEB)/ca.js",
    "$(WEB)/usa.js",
    "$(WEB)/state.js",
    "$(WEB)/world.js",
    "$(WEB)/rankstate.md",
    "$(WEB)/rankca.md",
    "$(CSS)/rankstate.scss",
    "$(CSS)/rankca.scss",
]

["web/data_world.js"]
deps = ["raw-data.json", "raw2data.js", "common.js"]
exec = "node raw2data.js $< >$@"

["web/data_ca.js"]
deps = ["time_series_covid19_deaths_US.csv", "ca_raw2data.js", "common.js"]
exec = "node ca_raw2data.js $< >$@"

["web/data_usa.js"]
deps = ["time_series_covid19_deaths_US.csv", "us_raw2data.js", "common.js"]
exec = "node us_raw2data.js $< >$@"

["web/data_state.js"]
deps = ["time_series_covid19_deaths_US.csv", "state_raw2data.js", "common.js"]
exec = "node state_raw2data.js $< >$@"

["$(WEB)/rank%.md"]
deps = ["web/data_%.js", "genrank_%_md.js"]
exec = "node genrank_%_md.js >$@"

["$(CSS)/rank%.scss"]
deps = ["web/data_%.js", "genrank_%_scss.js"]
exec = "node genrank_%_scss.js >$@"

["raw-data.json"]
exec = "wget --output-document=$@ https://opendata.ecdc.europa.eu/covid19/casedistribution/json/"

["time_series_covid19_deaths_US.csv"]
exec = "wget --output-document=$@ https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"

["$(WEB)/%.min.js"]
deps = ["web/%.js", "web/data_%.js", "web/graph.js", "web/passprint.js"]
exec = "$(ROLLUP) --plugin terser --input $<"

["$(WEB)/%.js"]
deps = ["web/%.js", "web/data_%.js", "web/graph.js"]
exec = "$(ROLLUP) --input $<"

[clean]
exec = """
rm -f web/data_world.js web/data_us.js web/data_state.js
rm -f raw-data.json time_series_covid19_deaths_US.csv
"""
