[copy]
deps = ["data.js", "index.js", "index.md"]
exec = "mkdir -p ../../covidgrowth && cp $+ *.csv ../../covidgrowth"

["data.js"]
deps = ["COVID-19-geographic-disbtribution-worldwide.xlsx", "xlsx2js.js"]
exec = "node xlsx2js.js $< >$@"

["COVID-19-geographic-disbtribution-worldwide.xlsx"]
exec = "wget https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx"

[clean]
exec = "rm -f data.js COVID-19-geographic-disbtribution-worldwide.xlsx"
